### ISSUE TITLE
general fixes

### ISSUE THREAD

**Issue by abdelazizElemary** [MuhammadSawalhy/udemy-clone#1]
- Fix the header when shrinking the page, the `<header />` disappears 
- you can better make the logo centered using flex properties
- remove all unnecessary tags, for example: `line 71` `<section /> tag`
- instead of using display as grid for the courses carousel, you can use flex-wrap

**Comment by MuhammadSawalhy** [comment]
What is meant by the first point? Do you mean that the `<header />` should disappear on small screens? I've just made identical to Udemy, so when the screen becomes small the `<header />` make the bell image and the card in a column, one in top of the other.

> * Fix the header when shrinking the page, the `<header />` disappears

**Comment by assawalhy** [comment]
> * you can better make the logo centered using flex properties

I have two icons to the right and only one icon to the left of the logo, so I need to shift the logo to the right to be in the centre.

To give it this little shift to the right to balance it in the centre I can do one of these options (for example):

1. Add an empty icon, or say icon placeholder **(this is what I did)**
2. Give it `position relative` and `left: var(--half-icon-width)`
3. Give it padding or margin to the left equals `var(--half-icon-width)`
4. ...etc

Perhaps there exists another solution by giving the logo `position: absolute` and then making it in the centre of the `<nav />` element.

![image](https://user-images.githubusercontent.com/42011920/184116869-1b89ec35-7487-43b7-bc73-45dbac0098cc.png)
